sudo:
  required

services:
    - elasticsearch
    - postgresql

addons:
  postgresql: "9.5"

dist:
  trusty

language:
  python

python:
  - 3.6

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"

install:
  - make install
  - pip install coveralls

script:
  - make test

before_script:
  - moto_server &
  - sleep 30
  - curl localhost:9200
  - curl localhost:5000
  - psql -U postgres -c "create user datahub password 'secret' createdb;"
  - psql -U postgres -c "create database datahq owner=datahub;"

after_success:
  - coveralls
